### ISSUE TITLE
Error -  genes with no literature data

### ISSUE THREAD

**Issue by sigven** [danro9685/OncoScore#10]
Hi,

I have just tried your software (v 1.0.0) in order to build a ranking of genes based on cancer relevance. During test runs, I experience that `OncoScore::perform.query` fail/crash if any gene in my submission list have no hits in PubMed (e.g. the gene [TBC1D3C](http://www.ncbi.nlm.nih.gov/gene/414060)) Here is the error message that appears:

`Error in if ((is.na(s1) || is.na(s2)) && (get.count.of.list(webget) ==  : 
  missing value where TRUE/FALSE needed
In addition: Warning messages:
`
[](url)

Sigve

**Comment by luca-dex** [comment]
I can't reproduce the issue:

```
> perform.query('TBC1D3C')
### Starting the queries for the selected genes.

### Performing queries for cancer literature 
    Number of papers found in PubMed for TBC1D3C was: -1 

### Performing queries for all the literature 
    Number of papers found in PubMed for TBC1D3C was: -1 
        CitationsGene CitationsGeneInCancer
TBC1D3C            -1                    -1
Warning messages:
1: In perform.query(c("TBC1D3C")) : TBC1D3C not found on PubMed

2: In perform.query(c("TBC1D3C")) : TBC1D3C not found on PubMed
```

**Comment by sigven** [comment]
Hi,

You are right. I do not see the error any longer (for whatever reason). You can close the issue.

**Comment by luca-dex** [comment]
:)
