### ISSUE TITLE
Error subscript out of bounds

### ISSUE THREAD

**Issue by Jumanah-y** [danro9685/OncoScore#14]
Hello,

Thank you for the amazing package.
I works for me fine for couple of gene lists but for a list perform.query() works fine but when I run compute.oncoscore() it produces this error:
Error in data[gene, "CitationsGene"] : subscript out of bounds

Could you kindly help me.
Thanks a lot.

**Comment by danro9685** [comment]
Dear @Jumanah-y, 

thank you for letting us know. Could you provide some data to replicate this error? 
I am also including @luca-dex in the conversation. 

Best, 
Daniele

**Comment by Jumanah-y** [comment]
Dear @luca-dex and @danro9685 

I have this list of genes:
 [1] ROBO2    NCKAP5   CNTNAP2  GRID2   
 [5] DLG2     RBFOX1   AGBL4    PARD3B  
 [9] KCNH7    AUTS2    PTEN     LSAMP   
[13] IMMP2L   PCDH15   PRKG1    EYS     
[17] TMPRSS2  PARK2    WWOX     PTPRD   
[21] CCSER1   NAALADL2 SHANK2   CSMD1   
[25] PDE4D    ERG      FHIT     MACROD2 
[29] LRP1B 

When I run perform.query function on the list I get this output:
         CitationsGene CitationsGeneInCancer
ROBO2              254                    45
NCKAP5               5                     2
CNTNAP2            313                    49
GRID2               64                    11
DLG2                81                    55
RBFOX1             136                    26
AGBL4                3                     1
PARD3B              25                     8
KCNH7               38                     6
AUTS2               80                    13
PTEN             13914                 11091
LSAMP               52                    22
IMMP2L              46                     8
PCDH15             167                    11
PRKG1              208                    34
EYS                366                   124
TMPRSS2            932                   848
PARK2            70210                  2762
WWOX               416                   399
PTPRD              175                   100
CCSER1               5                     2
NAALADL2            12                     5
SHANK2             159                    21
CSMD1              113                    45
PDE4D              532                    99
ERG               9596                  1907
FHIT              1127                  1098
MACROD2             50                    17
LRP1B              108                    69

However, when I run compute.oncoscore function, it produces this error:
### Processing data
Error in data[gene, "CitationsGene"] : subscript out of bounds

Not sure why because it worked on different list of genes. Has anything to do with the number of citations? 

Thank you,
Jumanah

**Comment by danro9685** [comment]
Dear @Jumanah-y, 

I just used the list of genes you mentioned: 

queries = perform.query(c("ROBO2","NCKAP5","CNTNAP2","GRID2","DLG2","RBFOX1","AGBL4","PARD3B","KCNH7","AUTS2","PTEN","LSAMP","IMMP2L","PCDH15","PRKG1","EYS","TMPRSS2","PARK2","WWOX","PTPRD","CCSER1","NAALADL2","SHANK2","CSMD1","PDE4D","ERG","FHIT","MACROD2","LRP1B"))

and then performed the OncoScore computation: 

oncoscores = compute.oncoscore(queries)
        Processing data
        Computing frequencies scores 
        Estimating oncogenes
        Results:
	 ROBO2 -> 15.78272 
	 NCKAP5 -> 22.77294 
	 CNTNAP2 -> 13.72374 
	 GRID2 -> 14.32292 
	 DLG2 -> 57.19101 
	 RBFOX1 -> 16.42026 
	 AGBL4 -> 12.30234 
	 PARD3B -> 25.10918 
	 KCNH7 -> 12.78077 
	 AUTS2 -> 13.67958 
	 PTEN -> 73.91807 
	 LSAMP -> 34.88586 
	 IMMP2L -> 14.24274 
	 PCDH15 -> 5.661886 
	 PRKG1 -> 14.2234 
	 EYS -> 29.90127 
	 TMPRSS2 -> 81.77326 
	 PARK2 -> 3.693022 
	 WWOX -> 84.88948 
	 PTPRD -> 49.47392 
	 CCSER1 -> 22.77294 
	 NAALADL2 -> 30.04404 
	 SHANK2 -> 11.40148 
	 CSMD1 -> 33.98401 
	 PDE4D -> 16.55398 
	 ERG -> 18.38033 
	 FHIT -> 87.81699 
	 MACROD2 -> 27.97575 
	 LRP1B -> 54.43072

Everything worked fine. So please try to run this again or let us know more details of the error. 

Best, 
Daniele
