### ISSUE TITLE
Error in get.list.from.xml(webget)

### ISSUE THREAD

**Issue by robinjugas** [danro9685/OncoScore#21]
Hello. 
I am getting two errors, somehow tied together. I am querying large number of genes and I got:

_Warning: Number of items was greater than expected. PARTIAL RESULTS USED [MaxRet needs to be increased]._

I discovered this is caused by gene named "TH". 
When I use
`perform.query("TH", gene.num.limit=100000)`
I got 
_Error in get.list.from.xml(webget) : 
  Warning: Number of items was different than the number of references._

I'll easily remove such a gene from a query. 
But it would be useful to handle this rare exception so it doesn't stop the whole query. 

Thank you for the package anyway, it does the job really well.
Regards,
Robin

**Comment by danro9685** [comment]
Dear @robinjugas,

Thanks for letting us know! I will close this issue as it seems you have fixed it from your side.
We will handle this in the package.

Thanks,
Daniele

**Comment by pjlaw** [comment]
Hi

I'm not sure if this is still being looked into but I'm getting the same error

```
query = perform.query(c("MYC"))
### Starting the queries for the selected genes.

### Performing queries for cancer literature 
Error in get.list.from.xml(webget) : 
  Warning: Number of items was different than the number of references.
```

I believe this is because this is a very well studied gene, so there are a lot of references being returned. In the `get.list.from.xml ` function:
```
> lc = get.count.of.list(webget)
> lc
[1] 37877
> length(ListItems)
[1] 9999

```
From the [ESearch documentation](https://www.ncbi.nlm.nih.gov/books/NBK25499/#chapter4.ESearch):

> retmax
> Total number of UIDs from the retrieved set to be shown in the XML output (default=20). By default, ESearch only includes the first 20 UIDs retrieved in the XML output. If usehistory is set to 'y', the remainder of the retrieved set will be stored on the History server; otherwise these UIDs are lost. Increasing retmax allows more of the retrieved UIDs to be included in the XML output, up to a maximum of 10,000 records.
> 
> To retrieve more than 10,000 UIDs from databases other than PubMed, submit multiple esearch requests while incrementing the value of retstart (see Application 3). For PubMed, ESearch can only retrieve the first 10,000 records matching the query. To obtain more than 10,000 PubMed records, consider using <EDirect> that contains additional logic to batch PubMed search results automatically so that an arbitrary number can be retrieved.

So even through retmax is set to 3000000 in the code, ESearch will only return the first 10,000

**Comment by MarcA-17** [comment]
Hi, 

I'm getting the same error when trying OncoScore with genes with lots of references (e.g., TP53, RB1, etc). Is there a way to run this tool with these type of genes? 

`perform.query("TP53")`

```
Error in get.list.from.xml(webget): Warning: Number of items was different than the number of references.
Traceback:

1. get.pubmed.driver.analysis(paste0(gene, search.fields), gene = gene)
2. get.list.from.xml(webget)
3. stop("Warning: Number of items was different than the number of references.")
4. .handleSimpleError(function (cnd) 
 . {
 .     watcher$capture_plot_and_output()
 .     cnd <- sanitize_call(cnd)
 .     watcher$push(cnd)
 .     switch(on_error, continue = invokeRestart("eval_continue"), 
 .         stop = invokeRestart("eval_stop"), error = invokeRestart("eval_error", 
 .             cnd))
 . }, "Warning: Number of items was different than the number of references.", 
 .     base::quote(get.list.from.xml(webget)))
```

**Comment by PaulaLopezMarti** [comment]
Hi everyone, 

I am running into the same issue when I try to query well-known genes (MYC, JAK2, etc). Has anyone found a way to run the code  properly with these genes?

Thanks a lot,

Paula
